[package]
name = "miku-ktls"
version = "7.0.0-rc.4"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/hanyu-dev/miku-ktls"
documentation = "https://docs.rs/miku-ktls"
authors = ["Amos Wenger <amos@bearcove.net>"]
readme = "README.md"
description = """
Configures kTLS for tokio-rustls client and server connections.
"""
rust-version = "1.71.0"

[dependencies]
futures-util = "0.3.31"
ktls-sys = { version = "1.1.0-rc.1", path = "../ktls-sys", package = "miku-ktls-sys"}
libc = { version = "0.2.172", features = ["const-extern-fn"] }
memoffset = "0.9.1"
nix = { version = "0.29.0", features = ["socket", "uio", "net"] }
num_enum = "0.7.3"
pin-project-lite = "0.2.16"
rustls = { version = "0.23.22", default-features = false }
smallvec = "1.15.0"
thiserror = "2.0.0"
tokio = { version = "1.39.0", features = ["net", "macros", "io-util"] }
tokio-rustls = { version = "0.26.2", default-features = false }
tracing = "0.1.40"

[dev-dependencies]
lazy_static = "1.5.0"
oorandom = "11.1.5"
rcgen = "0.13.2"
socket2 = "0.5.9"
test-case = "3.3.1"
tokio = { version = "1.39.0", features = ["full"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[features]
default = ["aws_lc_rs", "tls12"]

aws_lc_rs = ["aws-lc-rs"]                                  # Alias because Cargo features commonly use `-`
aws-lc-rs = ["rustls/aws_lc_rs", "tokio-rustls/aws_lc_rs"]
ring = ["rustls/ring", "tokio-rustls/ring"]
tls12 = ["rustls/tls12", "tokio-rustls/tls12"]
